/*!--------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define("vs/code/node/cliProcessMain.nls.es", {
  "vs/base/common/severity": ["Error", "Advertencia", "Información"],
  "vs/base/node/zip": ["{0} no se encontró dentro del archivo zip."],
  "vs/code/node/cliProcessMain": ["La extensión '{0}' no se encontró.", "La extensión '{0}' no está instalada.", "Asegúrese de usar el identificador de extensión completo, incluido el publicador, por ejemplo: {0}.", "La extensión '{0}' se ha instalado correctamente.", "Cancelar instalación de extensión '{0}'.", "La extensión '{0}' ya está instalada.", "Se encontró '{0}' en Marketplace.", "Instalando...", "La extensión '{0}' v{1} se instaló correctamente.", "Cancelar instalación de extensión '{0}'.", "Desinstalando {0}...", "La extensión '{0}' se desinstaló correctamente."],
  "vs/platform/configuration/common/configurationRegistry": ["La configuración predeterminada se reemplaza", "Establecer los valores de configuración que se reemplazarán para el lenguaje {0}.", "Establecer los valores de configuración que se reemplazarán para un lenguaje.", 'No se puede registrar "{0}". Coincide con el patrón de propiedad \'\\\\[.*\\\\]$\' para describir la configuración del editor específica del lenguaje. Utilice la contribución "configurationDefaults".', 'No se puede registrar "{0}". Esta propiedad ya está registrada.'],
  "vs/platform/extensionManagement/common/extensionManagement": ["Extensiones", "Preferencias"],
  "vs/platform/extensionManagement/node/extensionGalleryService": ["No se puede descargar porque no se encuentra la extensión compatible con la versión actual '{0}' de VS Code."],
  "vs/platform/extensionManagement/node/extensionManagementService": ["Extensión no válida: package.json no es un archivo JSON.", "Please restart Code before reinstalling {0}.", "Una versión más nueva de esta extensión ya está instalada. ¿Desea anular esto con la versión anterior?", "Anular", "Cancelar", "Error while installing dependencies. {0}", "No se puede instalar porque no se encuentra la extensión '{0}' compatible con la versión actual '{1}' del VS Code.", "No se puede instalar porque no se encuentra la extensión dependiente '{0}' compatible con la versión actual '{1}' del VS Code.", "No se puede instalar porque todavía se está ejecutando una instancia obsoleta de la extensión. Por favor, salga e inicie el VS Code antes de volver a instalarlo.\n", "No se puede instalar porque todavía se está ejecutando una instancia obsoleta de la extensión. Por favor, salga e inicie VS Code antes de volver a instalarlo.", "¿Quiere desinstalar solo '{0}' o también sus dependencias?", "Solo", "Todo", "Cancelar", "¿Seguro que quiere desinstalar '{0}'?", "Aceptar", "Cancelar", "No se puede desinstalar la extensión '{0}'. La extensión '{1}' depende de esta.", "No se puede desinstalar la extensión '{0}'. Las extensiones '{1}' y '{2}' dependen de esta.", "No se puede desinstalar la extensión '{0}'. Las extensiones '{1}' y '{2}', entre otras, dependen de esta.", "No se encontró la extensión."],
  "vs/platform/extensions/node/extensionValidator": ['No se pudo analizar el valor {0} de "engines.vscode". Por ejemplo, use: ^0.10.0, ^1.2.3, ^0.11.0, ^0.10.x, etc.', 'La versión indicada en "engines.vscode" ({0}) no es suficientemente específica. Para las versiones de vscode anteriores a la 1.0.0, defina como mínimo la versión principal y secundaria deseadas. Por ejemplo: ^0.10.0, 0.10.x, 0.11.0, etc.', 'La versión indicada en "engines.vscode" ({0}) no es suficientemente específica. Para las versiones de vscode posteriores a la 1.0.0, defina como mínimo la versión principal deseada. Por ejemplo: ^1.10.0, 1.10.x, 1.x.x, 2.x.x, etc.', "La extensión no es compatible con {0} de Code y requiere: {1}.", "Se obtuvo una descripción vacía de la extensión.", 'la propiedad `{0}` es obligatoria y debe ser de tipo "string"', 'la propiedad `{0}` es obligatoria y debe ser de tipo "string"', 'la propiedad `{0}` es obligatoria y debe ser de tipo "string"', 'la propiedad `{0}` es obligatoria y debe ser de tipo "object"', 'la propiedad `{0}` es obligatoria y debe ser de tipo "string"', 'la propiedad `{0}` se puede omitir o debe ser de tipo "string[]"', 'la propiedad `{0}` se puede omitir o debe ser de tipo "string[]"', "las propiedades `{0}` y `{1}` deben especificarse u omitirse conjuntamente", 'la propiedad `{0}` se puede omitir o debe ser de tipo "string"', 'Se esperaba que "main" ({0}) se hubiera incluido en la carpeta de la extensión ({1}). Esto puede hacer que la extensión no sea portátil.', "las propiedades `{0}` y `{1}` deben especificarse u omitirse conjuntamente", "La versión de la extensión no es compatible con semver."],
  "vs/platform/message/common/message": ["Cerrar", "Más tarde", "Cancelar", "...1 additional file not shown", "...{0} additional files not shown"],
  "vs/platform/request/node/request": ["HTTP", "El valor del proxy que se debe utilizar. Si no se establece, se tomará de las variables de entorno http_proxy y https_proxy", "Indica si el certificado del servidor proxy debe comprobarse en la lista de entidades de certificación proporcionada.", "Valor que debe enviarse como encabezado de 'Proxy-Authorization' para cada solicitud de red."],
  "vs/platform/telemetry/common/telemetryService": ["Telemetría", "Habilite los datos de uso y los errores para enviarlos a Microsoft."]
});
//# sourceMappingURL=https://ticino.blob.core.windows.net/sourcemaps/ca023a700f35212071dfe9544272719cbbf80e4c/core/vs\code\node\cliProcessMain.nls.es.js.map