/*!--------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define("vs/code/electron-browser/sharedProcess/sharedProcessMain.nls.tr", {
  "vs/base/common/severity": ["Hata", "Uyarı", "Bilgi"],
  "vs/base/node/zip": ["{0}, zip içerisinde bulunamadı."],
  "vs/platform/configuration/common/configurationRegistry": ["Varsayılan Yapılandırma Geçersiz Kılmaları", "{0} dili için geçersiz kılınacak düzenleyici ayarlarını yapılandırın.", "Bir dil için geçersiz kılınacak düzenleyici ayarlarını yapılandırın.", "'{0}' kaydedilemiyor. Bu, dile özgü düzenleyici ayarlarını tanımlamak için '\\\\[.*\\\\]$' özellik kalıbı ile eşleşir. 'configurationDefaults' ögesini kullanın.", "'{0}' kaydedilemiyor. Bu özellik zaten kayıtlı."],
  "vs/platform/extensionManagement/common/extensionManagement": ["Eklentiler", "Tercihler"],
  "vs/platform/extensionManagement/node/extensionGalleryService": ["İndirme başarısız oldu çünkü, eklentinin uyumlu olduğu VS Code'un '{0}' sürümü bulunamadı."],
  "vs/platform/extensionManagement/node/extensionManagementService": ["Eklenti geçersiz: package.json bir JSON dosyası değil.", "Please restart Code before reinstalling {0}.", "Bu eklentinin daha yeni bir sürümü zaten yüklü. Bunu, daha eski bir sürümle geçersiz kılmak ister misiniz?", "Geçersiz Kıl", "İptal", "Error while installing dependencies. {0}", "Yükleme başarısız oldu çünkü, '{0}' eklentisinin uyumlu olduğu VS Code'un '{1}' sürümü bulunamadı.", "Yükleme başarısız oldu çünkü, bağımlılığı bulunan '{0}' eklentisinin uyumlu olduğu VS Code'un '{1}' sürümü bulunamadı.", "Yükleme başarısız oldu çünkü, eklentinin eski bir örneği hâlâ çalışıyor. Yeniden yüklemeden önce lütfen VS Code'dan çıkın ve tekrar açın.", "Yükleme başarısız oldu çünkü, eklentinin eski bir örneği hâlâ çalışıyor. Yeniden yüklemeden önce lütfen VS Code'dan çıkın ve tekrar açın.", "Yalnızca '{0}' eklentisini mi yoksa bağımlılıklarını da kaldırmak ister misiniz?", "Sadece Eklenti", "Tümü", "İptal", "'{0}' eklentisini kaldırmak istediğinizden emin misiniz?", "Tamam", "İptal", "'{0}' eklentisi kaldırılamıyor. '{1}' eklentisi buna bağlı.", "'{0}' eklentisi kaldırılamıyor. '{1}' ve '{2}' eklentileri buna bağlı.", "'{0}' eklentisi kaldırılamıyor. '{1}, '{2}' eklentileri ve diğerleri buna bağlı.", "Eklenti bulunamadı"],
  "vs/platform/extensions/node/extensionValidator": ["`engines.vscode` değeri {0} ayrıştırılamadı. Lütfen örnekte verilenlere benzer ifadeler kullanın: ^0.10.0, ^1.2.3, ^0.11.0, ^0.10.x, vb.", "`engines.vscode`da belirtilen sürüm ({0}) yeterince belirli değil. vscode 1.0.0'dan önceki sürümler için, lütfen istenecek minimum majör ve minör sürüm numarasını tanımlayın. Örneğin: ^0.10.0, 0.10.x, 0.11.0, vb.", "`engines.vscode`da belirtilen sürüm ({0}) yeterince belirli değil. vscode 1.0.0'dan sonraki sürümler için, lütfen istenecek minimum majör sürüm numarasını tanımlayın. Örneğin: ^1.10.0, 1.10.x, 1.x.x, 2.x.x, vb.", "Eklenti, Code {0} ile uyumlu değil. Gereken sürüm: {1}.", "Boş eklenti açıklaması alındı", "`{0}` özelliği zorunludur ve `string` türünde olmalıdır", "`{0}` özelliği zorunludur ve `string` türünde olmalıdır", "`{0}` özelliği zorunludur ve `string` türünde olmalıdır", "`{0}` özelliği zorunludur ve `object` türünde olmalıdır", "`{0}` özelliği zorunludur ve `string` türünde olmalıdır", "`{0}` özelliği atlanabilir veya `string[]` türünde olmalıdır", "`{0}` özelliği atlanabilir veya `string[]` türünde olmalıdır", "`{0}` ve `{1}` özelliklerinin ikisi birden belirtilmeli veya ikisi birden atlanmalıdır", "`{0}` özelliği atlanabilir veya `string` türünde olmalıdır", "`main` ({0}) yolunun eklentinin klasörü içine ({1}) eklenmiş olacağı beklendi. Bu, eklentiyi taşınamaz yapabilir.", "`{0}` ve `{1}` özelliklerinin ikisi birden belirtilmeli veya ikisi birden atlanmalıdır", "Eklenti sürümü semver ile uyumlu değil."],
  "vs/platform/message/common/message": ["Kapat", "Daha Sonra", "İptal", "...1 additional file not shown", "...{0} additional files not shown"],
  "vs/platform/request/node/request": ["HTTP", "Kullanılacak proxy ayarı. Ayarlanmazsa, http_proxy ve https_proxy ortam değişkenlerinden alınır", "Proxy sunucu sertifikasının verilen Sertifika Yetkilileri listesine göre doğrulanması gerekip gerekmediği.", "Her ağ isteği için 'Proxy-Authorization' başlığı olarak gönderilecek değer."],
  "vs/platform/telemetry/common/telemetryService": ["Telemetri", "Kullanım verileri ve hataların Microsoft'a gönderilmesini etkinleştirin."]
});
//# sourceMappingURL=https://ticino.blob.core.windows.net/sourcemaps/ca023a700f35212071dfe9544272719cbbf80e4c/core/vs\code\electron-browser\sharedProcess\sharedProcessMain.nls.tr.js.map